# Generated by Django 4.2.3 on 2023-08-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_accessories_delete_accesories_bottoms_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='type',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='accessories',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bottoms',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tops',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
